name: Main Pipeline
on: [push]
jobs:
  MainPipeline:
    runs-on: ubuntu-latest
    env:
      COMMIT_ID: ${{ github.sha }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps: 
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker build -t $DOCKER_USERNAME/wai:$COMMIT_ID .
          
      - name: push
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_USERNAME/back:$COMMIT_ID
      - name: deploy
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          envs: DOCKER_USERNAME,COMMIT_ID
          script: /home/waiDevOpsAdmin/test/deploy_script.sh wai $DOCKER_USERNAME/wai:$COMMIT_ID
        
